services:
  php:
    platform: linux/amd64
    build: . # pakai Dockerfile di folder ini
    container_name: php_container
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql

  mysql:
    platform: linux/amd64
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdailymyjurnal
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql

volumes:
  mysql_data:
