server {
    listen 80;
    index login.html index.php; # Tentukan file yang harus dicari Nginx

    root /var/www/html; # Lokasi file di dalam container

    location / {
        try_files $uri $uri/ =404;
    }

    # Bagian penting untuk PHP
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        # Mengirim permintaan ke container 'app' (nama layanan di docker-compose) pada port 9000
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}